---
version: '3.0'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer1:/data
    ports:
      - 8000:8000
      - 9000:9000
    restart: always

volumes:
  portainer1: